"""add part_category column to transactions table

Revision ID: ca7d0370f10f
Revises: 3037c2dd5e0f
Create Date: 2025-08-19 18:41:07.310872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7d0370f10f'
down_revision: Union[str, Sequence[str], None] = '3037c2dd5e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_expenses', sa.Column('recorded_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operational_expenses', 'users', ['recorded_by_user_id'], ['id'])
    op.add_column('stock_purchases', sa.Column('recorded_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_purchases', 'users', ['recorded_by_user_id'], ['id'])
    op.add_column('transactions', sa.Column('recorded_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['recorded_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'recorded_by_user_id')
    op.drop_constraint(None, 'stock_purchases', type_='foreignkey')
    op.drop_column('stock_purchases', 'recorded_by_user_id')
    op.drop_constraint(None, 'operational_expenses', type_='foreignkey')
    op.drop_column('operational_expenses', 'recorded_by_user_id')
    # ### end Alembic commands ###
