"""add recorded_by columns to data tables

Revision ID: 3037c2dd5e0f
Revises: a906b6da710c
Create Date: 2025-08-19 18:16:48.410222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3037c2dd5e0f'
down_revision: Union[str, Sequence[str], None] = 'a906b6da710c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
